### PR TITLE
support for unsigned int type

### PR DESCRIPTION
**Pull request by assaron**
I've added support for unsigned type. It has the same limitation as current int64 support - there will be overflow without a warning.

### CODE REVIEW

**Comment by assaron** [comment]
Here is an archive with the test h5 file.

[test_numbers.zip](https://github.com/vjcitn/rhdf5client/files/12564029/test_numbers.zip)

**Comment by assaron** [comment]
@vjcitn reminding you about this PR

**Comment by vjcitn** [comment]
is this still needed?

**Comment by assaron** [comment]
Yes!

**Comment by assaron** [comment]
@vjcitn Do you need some help with this? I think it should be still in a good shape, but let me know if I should do anything

**Comment by vjcitn** [comment]
Sorry for the delay on this.  I synchronized main branch of my repo with bioconductor git.  Can you look at the version number in DESCRIPTION, case of biocViews field, and revise PR a little then I will merge and then update bioconductor

**Comment by assaron** [comment]
I've updated the version. Not sure what you meant about biocViews, it looks to be correct.

One thing to note is that the tests are failing in this version, as they require test_numbers.h5 file to be uploaded to the HSDS. This is the archive with the file: https://github.com/vjcitn/rhdf5client/files/12564029/test_numbers.zip

**Comment by vjcitn** [comment]
the numbers file was added to hsds and the PR was merged and ported to bioconductor git

**Comment by assaron** [comment]
Great, thank you!

**Pull request merged**
