### PR TITLE
Fix for string-only compounds + add reporting of request errors

### PR DESCRIPTION
**Pull request by assaron**

### CODE REVIEW

**Comment by vjcitn** [comment]
Would you please bump version in DESCRIPTION with any PR?  Thanks

**Comment by assaron** [comment]
Yes, sorry, now it should be with the proper version.

**Comment by vjcitn** [comment]
I may have missed this.  But it looks like the hsdshdflab.hdfgroup.org is not working right now.  Do you think it would be possible to emulate the tests in hdf5 data that we could install at our bioconductor service?

**Comment by assaron** [comment]
@vjcitn Hi, I think  hsdshdflab.hdfgroup.org is up right now. 

>  Do you think it would be possible to emulate the tests in hdf5 data that we could install at our bioconductor service?

Not sure what you mean. What exactly is your bioconductor service?

**Comment by vjcitn** [comment]
hi @assaron -- what I mean is that if you can grab the hdf5 entities that your tests use, from the hdfgroup services that is being shut down, then I can add them to our bioconductor hsds system so that your tests can run against those with the proper URL.

**Comment by assaron** [comment]
@vjcitn got you. I've committed a generator for test files (not sure where to put the actual files) and changed the test accordingly (but they're failing, as the url is incorrect). Is that what you meant? Is there a public url for bioconductor hsds service?

**Comment by vjcitn** [comment]
The bioconductor hsds is at `https://hsdsdev.bioconductor.org` -- i have uploaded your files.  I think I have to change the src values in the tests.
```
  hsload /home/stvjc/HSDS/alexey/inst/test_scalar.h5 /shared/bioconductor/test_scalar.h5
  hsacl /shared/bioconductor/test_scalar.h5 +re default
       username     create      read    update    delete   readACL  updateACL 
--------------------------------------------------------------------------------
        default      False      True     False     False      True     False 
  hsload /home/stvjc/HSDS/alexey/inst/test_string.h5 /shared/bioconductor/test_string.h5
  hsacl /shared/bioconductor/test_string.h5 +re default
       username     create      read    update    delete   readACL  updateACL 
--------------------------------------------------------------------------------
        default      False      True     False     False      True     False 
  hsload /home/stvjc/HSDS/alexey/inst/test_compound.h5 /shared/bioconductor/test_compound.h5
  hsacl /shared/bioconductor/test_compound.h5 +re default
       username     create      read    update    delete   readACL  updateACL 
--------------------------------------------------------------------------------
        default      False      True     False     False      True     False 
```

**Comment by vjcitn** [comment]
the tests are all revised and passing

**Comment by assaron** [comment]
Great, thanks!

**Pull request merged**
